---
- name: Update Apache server
  hosts: node1
  become: yes
  tasks:
  - name: copy war file in tomcat server
    copy:
     src: /home/centos/workspace/DepoywarUsingAnsible/target/WebAppCal-1.3.6.war
     dest: /home/ec2-user/apache-tomcat-7.0.94/webapps
...
~

